/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeIndexImport } from './routes/home.index'
import { Route as AboutIndexImport } from './routes/about.index'
import { Route as DetailsItemIdImport } from './routes/details.$itemId'

// Create/Update Routes

const HomeIndexRoute = HomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const DetailsItemIdRoute = DetailsItemIdImport.update({
  path: '/details/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/details/$itemId': {
      preLoaderRoute: typeof DetailsItemIdImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DetailsItemIdRoute,
  AboutIndexRoute,
  HomeIndexRoute,
])

/* prettier-ignore-end */
